bmad:
  version: "4.45.0"
  
agents:
  - id: "pm"
    name: "Product Manager"
    role: "product-manager"
    active: true
  - id: "dev"  
    name: "Developer"
    role: "developer"
    active: true

workflows:
  story_creation:
    enabled: true
    default_template: "story-tmpl.yaml"
    
tasks:
  document_creation:
    enabled: true
    default_format: "markdown"
    
preferences:
  language: "en"
  timezone: "UTC"
