version: 1.0.0
teamRoles:
  project-manager:
    name: Project Manager
    description: Oversees project planning, coordination, and delivery
    responsibilities:
      - Project planning and scheduling
      - Resource allocation and management
      - Risk assessment and mitigation
      - Stakeholder communication
      - Progress tracking and reporting
    agents:
      - pm
  developer:
    name: Developer
    description: Handles software development and technical implementation
    responsibilities:
      - Code development and implementation
      - Technical architecture design
      - Code review and quality assurance
      - Testing and debugging
      - Documentation and maintenance
    agents:
      - dev
  analyst:
    name: Business Analyst
    description: Analyzes requirements and provides business insights
    responsibilities:
      - Requirements gathering and analysis
      - Business process modeling
      - Data analysis and insights
      - Solution design and validation
      - Stakeholder requirement translation
    agents:
      - ba
paths:
  agents: .lcagents/agents
  tasks: .lcagents/tasks
  templates: .lcagents/templates
  checklists: .lcagents/checklists
  data: .lcagents/data
  utils: .lcagents/utils
  workflows: .lcagents/workflows
  agent-teams: .lcagents/agent-teams
github:
  integration: true
  copilotFeatures: true
  repository: ""
  branch: main
customization: {}
